package org.propertymanagement;

import org.propertymanagement.util.CorrelationIdLog;

import java.util.Map;
import java.util.concurrent.Callable;

public class TestCorrelationIdLogUtils implements CorrelationIdLog {
    @Override
    public void execWithAutogeneratedCorrelationId(String correlationIdPrefix, Runnable action) {
        action.run();
    }

    @Override
    public <V> V execWithAutogeneratedCorrelationId(String correlationIdPrefix, Callable<V> action) {
        try {
            return action.call();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void execWithProvidedCorrelationId(String correlationId, Runnable action) {
        action.run();
    }

    @Override
    public <V> V execWithProvidedCorrelationId(String correlationId, Callable<V> action) {
        try {
            return action.call();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public String getCorrelationId() {
        return "test";
    }

    @Override
    public Map<String, String> getCopyOfContextMap() {
        return Map.of();
    }

    @Override
    public void setContextMap(Map<String, String> contextMap) {
        // Do nothing
    }
}
